# Generated by Django 3.0.1 on 2019-12-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings_flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('sectorcode', models.CharField(max_length=50)),
                ('sectorname', models.CharField(max_length=100)),
            ],
        ),
    ]
